site_name: Flurl
site_description: Fluent URL building and wrist-friendly HTTP client for .NET
site_author: Todd Menier

extra:
    show_announcement: true

repo_url: https://github.com/tmenier/Flurl
edit_uri: '' #forces theme to create "GitHub" link (to repo) instead of "Edit on GitHub"

theme:
    name: darkly
    custom_dir: theme
    navigation_depth: 3
    highlightjs: true
    hljs_style: vs2015
    analytics:
        gtag: G-98NG0HGG6X

docs_dir: content
extra_css:
    - css/extra.css
    - https://fonts.googleapis.com/css?family=Leckerli+One|Lobster
extra_javascript:
    - js/extra.js

nav:
    - Home: index.md
    - Docs:
        - Fluent URL Building: docs/fluent-url.md
        - Fluent HTTP: docs/fluent-http.md
        - Testable HTTP: docs/testable-http.md
        - Managing Clients: docs/clients.md
        - Configuration: docs/configuration.md
        - Extensibility: docs/extensibility.md
        - Upgrading from 3.x: docs/upgrade.md

markdown_extensions:
    - toc:
        permalink: ☍
    - extra